import { reactive, ref } from 'vue'

const currentLang = ref('en')

const translations = {
  en: {
    nav: {
      home: 'Home',
      services: 'Services',
      cases: 'Cases',
      about: 'About',
      blog: 'Blog',
      contacts: 'Contacts',
      startProject: 'Start project',
    },
    hero: {
      badge: 'Available for new projects',
      title1: 'Digital solutions that',
      titleGrad: 'help businesses',
      title2: 'grow.',
      sub: 'We build modern websites, automation systems and marketing strategies that help companies scale faster and smarter.',
      btnPrimary: 'Start a project',
      btnSecondary: 'Get consultation',
      stat1Val: '80+',
      stat1Label: 'Projects delivered',
      stat2Val: '4.9★',
      stat2Label: 'Client satisfaction',
      stat3Val: '3×',
      stat3Label: 'Avg. growth rate',
      stat4Val: '5yr',
      stat4Label: 'Experience',
    },
    services: {
      tag: 'What we do',
      title: 'Services that drive',
      titleGrad: 'real results',
      sub: 'End-to-end digital solutions built for scale — from first pixel to continuous growth.',
      learnMore: 'Learn more →',
      items: [
        { icon: '🌐', title: 'Web Development', desc: 'High-performance websites and web apps built with modern stacks. Fast, secure, and conversion-optimized.' },
        { icon: '🎨', title: 'UI/UX Design', desc: 'User-centered interfaces that look premium and feel intuitive. From wireframes to pixel-perfect design systems.' },
        { icon: '📱', title: 'SMM Marketing', desc: 'Brand storytelling and community building that converts followers into loyal customers and brand advocates.' },
        { icon: '🎯', title: 'Target Advertising', desc: 'Precision ad campaigns across platforms. Data-driven targeting that maximizes ROAS and minimizes waste.' },
        { icon: '🤖', title: 'Chatbot Development', desc: 'Intelligent Telegram & Instagram automation for lead capture, support and sales flows that work 24/7.' },
        { icon: '📊', title: 'Business Analytics', desc: 'Custom BI dashboards and data pipelines that transform raw numbers into actionable business intelligence.' },
      ],
    },
    cases: {
      tag: 'Portfolio',
      title: 'Selected',
      titleGrad: 'case studies',
      sub: 'Real projects, real results. Here\'s how we\'ve helped businesses transform.',
      viewAll: 'View all projects →',
      labelIndustry: 'Industry',
      labelProblem: 'Problem',
      labelSolution: 'Solution',
      labelResult: 'Result',
      items: [
        { icon: '🏪', gradient: 'linear-gradient(135deg,#0f2027,#203a43,#2c5364)', industry: 'E-commerce', name: 'ShopFlow Platform', problem: 'Outdated store with poor mobile UX', solution: 'Full redesign + headless commerce', result: '+180% conversions in 60 days' },
        { icon: '🤖', gradient: 'linear-gradient(135deg,#1a1a2e,#16213e,#0f3460)', industry: 'SaaS / Fintech', name: 'TeleBot CRM', problem: 'Manual lead processing, high churn', solution: 'Telegram bot + CRM automation pipeline', result: '-70% response time, +40% retention' },
        { icon: '📊', gradient: 'linear-gradient(135deg,#0f0c29,#302b63,#24243e)', industry: 'Real Estate', name: 'PropVision Analytics', problem: 'No visibility into sales funnel data', solution: 'Custom BI dashboard + data pipeline', result: '3× faster decision-making' },
        { icon: '🌱', gradient: 'linear-gradient(135deg,#11998e,#0f4c3a,#0a2e2a)', industry: 'Health & Wellness', name: 'GreenLife Brand', problem: 'Zero digital presence, low awareness', solution: 'Brand identity + SMM + targeted ads', result: '+320% social reach in 3 months' },
      ],
    },
    process: {
      tag: 'How we work',
      title: 'Our proven',
      titleGrad: '4-step process',
      sub: 'A clear, transparent workflow that delivers consistently — on time and on budget.',
      steps: [
        { num: '01', title: 'Research', desc: 'Deep-dive into your business, market and competitors. Define goals, KPIs and roadmap.' },
        { num: '02', title: 'Design', desc: 'Iterative design sprints delivering high-fidelity prototypes with your feedback built in.' },
        { num: '03', title: 'Development', desc: 'Clean, scalable engineering with daily progress updates and transparent communication.' },
        { num: '04', title: 'Launch', desc: 'Rigorous QA, smooth deployment, and continuous optimization to compound growth.' },
      ],
    },
    testimonials: {
      tag: 'Social proof',
      title: 'Clients who',
      titleGrad: 'trust us',
      items: [
        { text: '"Rework transformed our online presence completely. The new website loads in under 2 seconds and our lead generation tripled within the first month."', name: 'Alexei Komarov', role: 'CEO, TechStart LLC', initials: 'AK', grad: 'linear-gradient(135deg,#3B82F6,#8B5CF6)' },
        { text: '"Their Telegram bot automation saved us 40+ hours per week. The team understood our workflow immediately and built exactly what we needed."', name: 'Diana Nazarova', role: 'Head of Operations, GrowthCo', initials: 'DN', grad: 'linear-gradient(135deg,#8B5CF6,#3B82F6)' },
        { text: '"The BI dashboard gave us real-time insight into our business for the first time. Game changer for decision-making at the executive level."', name: 'Roman Mukhitdinov', role: 'CFO, PropVision Group', initials: 'RM', grad: 'linear-gradient(135deg,#059669,#3B82F6)' },
      ],
    },
    cta: {
      tag: 'Ready to scale?',
      title: "Let's grow your",
      titleGrad: 'business together',
      sub: 'Book a free 30-minute strategy call. No commitment, just clarity.',
      btnPrimary: 'Start a project',
      btnTelegram: 'Chat on Telegram',
    },
    contact: {
      tag: 'Get in touch',
      title: 'Tell us about your',
      titleGrad: 'project',
      sub: 'We respond within 4 hours on business days. Let\'s talk about your goals.',
      labelName: 'Your name',
      labelEmail: 'Email address',
      labelCompany: 'Company / Website',
      labelDesc: 'Project description',
      placeholderName: 'John Smith',
      placeholderEmail: 'john@company.com',
      placeholderCompany: 'company.com (optional)',
      placeholderDesc: 'Tell us about your project, goals, and timeline...',
      submit: 'Send message',
      submitted: '✓ Message sent!',
      telegramLabel: 'Telegram',
      telegramHandle: '@Rework_AssistantBot',
      emailLabel: 'Email',
      emailVal: 'hello@reworkagency.com',
      locationLabel: 'Location',
      locationVal: 'Tashkent, Uzbekistan',
    },
    footer: {
      tagline: 'Digital solutions that help businesses grow through modern web, automation and data-driven marketing.',
      services: 'Services',
      company: 'Company',
      contact: 'Contact',
      copyright: '© 2025 Rework Agency. All rights reserved.',
      links: {
        webDev: 'Web Development',
        uiux: 'UI/UX Design',
        ads: 'Target Advertising',
        smm: 'SMM Marketing',
        chatbot: 'Chatbot Dev',
        bi: 'BI Analytics',
        home: 'Home',
        cases: 'Cases',
        about: 'About',
        blog: 'Blog',
        contacts: 'Contacts',
        telegram: 'Telegram Bot',
        instagram: 'Instagram',
        linkedin: 'LinkedIn',
      },
    },
    pages: {
      servicesTitle: 'All Services',
      servicesSub: 'Everything you need to grow your business digitally.',
      casesTitle: 'Case Studies',
      casesSub: 'Real projects with measurable results.',
      aboutTitle: 'About Rework Agency',
      aboutSub: 'We are a team of designers, engineers and growth strategists.',
      aboutBody: 'Founded in 2019, Rework Agency has helped 80+ companies across e-commerce, fintech, real estate and wellness transform their digital presence. We believe great digital products are built at the intersection of strategy, design and engineering — and we bring all three under one roof.',
      blogTitle: 'Blog & Insights',
      blogSub: 'Thoughts on design, growth and digital transformation.',
      contactsTitle: 'Contact Us',
      contactsSub: 'Let\'s discuss your project.',
    },
  },

  ru: {
    nav: {
      home: 'Главная',
      services: 'Услуги',
      cases: 'Кейсы',
      about: 'О нас',
      blog: 'Блог',
      contacts: 'Контакты',
      startProject: 'Начать проект',
    },
    hero: {
      badge: 'Открыты для новых проектов',
      title1: 'Цифровые решения, которые',
      titleGrad: 'помогают бизнесу',
      title2: 'расти.',
      sub: 'Мы создаём современные сайты, системы автоматизации и маркетинговые стратегии для масштабирования бизнеса.',
      btnPrimary: 'Начать проект',
      btnSecondary: 'Получить консультацию',
      stat1Val: '80+',
      stat1Label: 'Проектов сдано',
      stat2Val: '4.9★',
      stat2Label: 'Удовлетворённость',
      stat3Val: '3×',
      stat3Label: 'Средний рост',
      stat4Val: '5 лет',
      stat4Label: 'Опыта',
    },
    services: {
      tag: 'Что мы делаем',
      title: 'Услуги, которые дают',
      titleGrad: 'реальные результаты',
      sub: 'Комплексные цифровые решения для роста вашего бизнеса.',
      learnMore: 'Узнать больше →',
      items: [
        { icon: '🌐', title: 'Веб-разработка', desc: 'Высокопроизводительные сайты и веб-приложения на современных технологиях.' },
        { icon: '🎨', title: 'UI/UX Дизайн', desc: 'Интерфейсы, ориентированные на пользователя. От вайрфреймов до дизайн-систем.' },
        { icon: '📱', title: 'SMM Маркетинг', desc: 'Продвижение в соцсетях, которое превращает подписчиков в клиентов.' },
        { icon: '🎯', title: 'Таргетированная реклама', desc: 'Точные рекламные кампании с максимальным ROAS и минимальными потерями.' },
        { icon: '🤖', title: 'Чат-боты', desc: 'Автоматизация в Telegram и Instagram: лиды, поддержка, продажи 24/7.' },
        { icon: '📊', title: 'Бизнес-аналитика', desc: 'BI-дашборды и пайплайны данных для принятия взвешенных решений.' },
      ],
    },
    cases: {
      tag: 'Портфолио',
      title: 'Избранные',
      titleGrad: 'кейсы',
      sub: 'Реальные проекты с измеримыми результатами.',
      viewAll: 'Смотреть все проекты →',
      labelIndustry: 'Индустрия',
      labelProblem: 'Проблема',
      labelSolution: 'Решение',
      labelResult: 'Результат',
      items: [
        { icon: '🏪', gradient: 'linear-gradient(135deg,#0f2027,#203a43,#2c5364)', industry: 'E-commerce', name: 'ShopFlow Platform', problem: 'Устаревший магазин с плохим мобильным UX', solution: 'Полный редизайн + headless commerce', result: '+180% конверсий за 60 дней' },
        { icon: '🤖', gradient: 'linear-gradient(135deg,#1a1a2e,#16213e,#0f3460)', industry: 'SaaS / Fintech', name: 'TeleBot CRM', problem: 'Ручная обработка лидов, высокий отток', solution: 'Telegram-бот + автоматизация CRM', result: '-70% времени ответа, +40% удержание' },
        { icon: '📊', gradient: 'linear-gradient(135deg,#0f0c29,#302b63,#24243e)', industry: 'Недвижимость', name: 'PropVision Analytics', problem: 'Нет видимости воронки продаж', solution: 'Кастомный BI-дашборд + пайплайн данных', result: 'Принятие решений в 3× быстрее' },
        { icon: '🌱', gradient: 'linear-gradient(135deg,#11998e,#0f4c3a,#0a2e2a)', industry: 'Health & Wellness', name: 'GreenLife Brand', problem: 'Нулевое цифровое присутствие', solution: 'Брендинг + SMM + таргет', result: '+320% охват за 3 месяца' },
      ],
    },
    process: {
      tag: 'Как мы работаем',
      title: 'Наш проверенный',
      titleGrad: 'процесс из 4 шагов',
      sub: 'Прозрачный рабочий процесс — в срок и в бюджет.',
      steps: [
        { num: '01', title: 'Исследование', desc: 'Анализ бизнеса, рынка и конкурентов. Определяем цели, KPI и дорожную карту.' },
        { num: '02', title: 'Дизайн', desc: 'Итерационные дизайн-спринты с высококачественными прототипами.' },
        { num: '03', title: 'Разработка', desc: 'Чистый, масштабируемый код с ежедневными обновлениями.' },
        { num: '04', title: 'Запуск', desc: 'Строгое QA, плавный деплой и непрерывная оптимизация.' },
      ],
    },
    testimonials: {
      tag: 'Отзывы',
      title: 'Клиенты, которые нам',
      titleGrad: 'доверяют',
      items: [
        { text: '"Rework полностью преобразовал наше онлайн-присутствие. Сайт загружается менее чем за 2 секунды, а генерация лидов утроилась за первый месяц."', name: 'Алексей Комаров', role: 'CEO, TechStart LLC', initials: 'АК', grad: 'linear-gradient(135deg,#3B82F6,#8B5CF6)' },
        { text: '"Автоматизация через Telegram-бот сэкономила нам 40+ часов в неделю. Команда сразу поняла наши процессы."', name: 'Диана Назарова', role: 'Операционный директор, GrowthCo', initials: 'ДН', grad: 'linear-gradient(135deg,#8B5CF6,#3B82F6)' },
        { text: '"BI-дашборд впервые дал нам понимание бизнеса в реальном времени. Настоящий прорыв в принятии решений."', name: 'Роман Мухитдинов', role: 'CFO, PropVision Group', initials: 'РМ', grad: 'linear-gradient(135deg,#059669,#3B82F6)' },
      ],
    },
    cta: {
      tag: 'Готовы к росту?',
      title: 'Давайте вместе развивать',
      titleGrad: 'ваш бизнес',
      sub: 'Запишитесь на бесплатный 30-минутный стратегический звонок.',
      btnPrimary: 'Начать проект',
      btnTelegram: 'Написать в Telegram',
    },
    contact: {
      tag: 'Связаться с нами',
      title: 'Расскажите о',
      titleGrad: 'вашем проекте',
      sub: 'Мы отвечаем в течение 4 часов в рабочие дни.',
      labelName: 'Ваше имя',
      labelEmail: 'Email адрес',
      labelCompany: 'Компания / Сайт',
      labelDesc: 'Описание проекта',
      placeholderName: 'Иван Иванов',
      placeholderEmail: 'ivan@company.com',
      placeholderCompany: 'company.com (необязательно)',
      placeholderDesc: 'Расскажите о проекте, целях и сроках...',
      submit: 'Отправить сообщение',
      submitted: '✓ Сообщение отправлено!',
      telegramLabel: 'Telegram',
      telegramHandle: '@reworkagencybot',
      emailLabel: 'Email',
      emailVal: 'hello@reworkagency.com',
      locationLabel: 'Местоположение',
      locationVal: 'Ташкент, Узбекистан',
    },
    footer: {
      tagline: 'Цифровые решения для роста бизнеса через современный веб, автоматизацию и маркетинг.',
      services: 'Услуги',
      company: 'Компания',
      contact: 'Контакты',
      copyright: '© 2025 Rework Agency. Все права защищены.',
      links: {
        webDev: 'Веб-разработка',
        uiux: 'UI/UX Дизайн',
        ads: 'Таргет реклама',
        smm: 'SMM',
        chatbot: 'Чат-боты',
        bi: 'BI-аналитика',
        home: 'Главная',
        cases: 'Кейсы',
        about: 'О нас',
        blog: 'Блог',
        contacts: 'Контакты',
        telegram: 'Telegram Бот',
        instagram: 'Instagram',
        linkedin: 'LinkedIn',
      },
    },
    pages: {
      servicesTitle: 'Все услуги',
      servicesSub: 'Всё необходимое для цифрового роста вашего бизнеса.',
      casesTitle: 'Кейсы',
      casesSub: 'Реальные проекты с измеримыми результатами.',
      aboutTitle: 'О Rework Agency',
      aboutSub: 'Мы — команда дизайнеров, инженеров и стратегов роста.',
      aboutBody: 'Основанное в 2019 году, агентство Rework помогло 80+ компаниям в сферах e-commerce, fintech, недвижимости и wellness преобразовать их цифровое присутствие.',
      blogTitle: 'Блог и инсайты',
      blogSub: 'Мысли о дизайне, росте и цифровой трансформации.',
      contactsTitle: 'Связаться с нами',
      contactsSub: 'Обсудим ваш проект.',
    },
  },

  uz: {
    nav: {
      home: 'Bosh sahifa',
      services: 'Xizmatlar',
      cases: 'Loyihalar',
      about: 'Biz haqimizda',
      blog: 'Blog',
      contacts: 'Aloqa',
      startProject: 'Loyiha boshlash',
    },
    hero: {
      badge: 'Yangi loyihalar uchun ochiqmiz',
      title1: 'Biznesga',
      titleGrad: 'o\'sishga yordam',
      title2: 'beruvchi raqamli yechimlar.',
      sub: 'Biz kompaniyalarga tezroq o\'sishga yordam beradigan zamonaviy veb-saytlar, avtomatlashtirish tizimlari va marketing strategiyalari yaratamiz.',
      btnPrimary: 'Loyiha boshlash',
      btnSecondary: 'Konsultatsiya olish',
      stat1Val: '80+',
      stat1Label: 'Topshirilgan loyihalar',
      stat2Val: '4.9★',
      stat2Label: 'Mijoz mamnuniyati',
      stat3Val: '3×',
      stat3Label: "O'rtacha o'sish",
      stat4Val: '5yil',
      stat4Label: 'Tajriba',
    },
    services: {
      tag: 'Biz nima qilamiz',
      title: "Haqiqiy natija beruvchi",
      titleGrad: 'xizmatlar',
      sub: "Birinchi pikseldan doimiy o'sishgacha — to'liq raqamli yechimlar.",
      learnMore: "Ko'proq →",
      items: [
        { icon: '🌐', title: 'Veb-ishlab chiqish', desc: "Zamonaviy texnologiyalarda qurilgan yuqori samarali veb-saytlar va ilovalar." },
        { icon: '🎨', title: 'UI/UX Dizayn', desc: "Premium ko'rinadigan va intuitiv his etiluvchi foydalanuvchi interfeyslari." },
        { icon: '📱', title: 'SMM Marketing', desc: "Kuzatuvchilarni sadoqatli mijozlarga aylantiradigan brend tarixi va jamiyat qurilishi." },
        { icon: '🎯', title: 'Maqsadli reklama', desc: "ROAS ni maksimallashtiruvchi aniq reklama kampaniyalari." },
        { icon: '🤖', title: 'Chatbot ishlab chiqish', desc: "Telegram va Instagram avtomatlashtirish: qo'rg'oshin qo'lga kiritish, qo'llab-quvvatlash, 24/7 savdo." },
        { icon: '📊', title: 'Biznes tahlili', desc: "Xom ma'lumotlarni harakat qilish mumkin bo'lgan biznes intellektiga aylantiradigan BI panellari." },
      ],
    },
    cases: {
      tag: 'Portfolio',
      title: 'Tanlangan',
      titleGrad: 'loyihalar',
      sub: "Haqiqiy loyihalar, haqiqiy natijalar.",
      viewAll: "Barcha loyihalarni ko'rish →",
      labelIndustry: 'Soha',
      labelProblem: 'Muammo',
      labelSolution: 'Yechim',
      labelResult: 'Natija',
      items: [
        { icon: '🏪', gradient: 'linear-gradient(135deg,#0f2027,#203a43,#2c5364)', industry: 'E-commerce', name: 'ShopFlow Platform', problem: "Yomon mobil UX bilan eskirgan do'kon", solution: 'To\'liq qayta dizayn + headless commerce', result: "60 kunda +180% konversiya" },
        { icon: '🤖', gradient: 'linear-gradient(135deg,#1a1a2e,#16213e,#0f3460)', industry: 'SaaS / Fintech', name: 'TeleBot CRM', problem: "Qo'lda qo'rg'oshin qayta ishlash", solution: 'Telegram bot + CRM avtomatlashtirish', result: "-70% javob vaqti, +40% ushlab qolish" },
        { icon: '📊', gradient: 'linear-gradient(135deg,#0f0c29,#302b63,#24243e)', industry: "Ko'chmas mulk", name: 'PropVision Analytics', problem: "Savdo hunisi ma'lumotlariga ko'rinmaslik", solution: "Maxsus BI paneli + ma'lumotlar quvuri", result: "3× tezroq qaror qabul qilish" },
        { icon: '🌱', gradient: 'linear-gradient(135deg,#11998e,#0f4c3a,#0a2e2a)', industry: 'Sog\'liq', name: 'GreenLife Brand', problem: "Raqamli mavjudlik yo'q", solution: 'Brend + SMM + maqsadli reklamalar', result: "3 oyda +320% ijtimoiy qamrov" },
      ],
    },
    process: {
      tag: 'Qanday ishlashimiz',
      title: "Sinovdan o'tgan",
      titleGrad: '4 bosqichli jarayonimiz',
      sub: "Har doim o'z vaqtida va byudjet doirasida — aniq, shaffof ish oqimi.",
      steps: [
        { num: '01', title: 'Tadqiqot', desc: "Biznesingiz, bozoringiz va raqobatchilaringizni chuqur o'rganish." },
        { num: '02', title: 'Dizayn', desc: "Yuqori sifatli prototiplar bilan takroriy dizayn sprintlari." },
        { num: '03', title: 'Ishlab chiqish', desc: "Kunlik yangilanishlar bilan toza, miqyosli muhandislik." },
        { num: '04', title: 'Ishga tushirish', desc: "Qat'iy QA, silliq joylashtirish va doimiy optimallashtirish." },
      ],
    },
    testimonials: {
      tag: 'Ijtimoiy isbot',
      title: 'Bizga ishonuvchi',
      titleGrad: 'mijozlar',
      items: [
        { text: '"Rework bizning onlayn mavjudligimizni butunlay o\'zgartirdi. Yangi veb-sayt 2 soniyadan kam vaqtda yuklanadi va birinchi oyda qo\'rg\'oshin avlodimiz uch baravar ko\'paydi."', name: 'Aleksey Komarov', role: 'CEO, TechStart LLC', initials: 'AK', grad: 'linear-gradient(135deg,#3B82F6,#8B5CF6)' },
        { text: '"Ularning Telegram bot avtomatlashtirishi bizga haftasiga 40+ soat tejadi. Jamoa bizning ish jarayonimizni darhol tushundi."', name: 'Diana Nazarova', role: "Operatsiyalar boshlig'i, GrowthCo", initials: 'DN', grad: 'linear-gradient(135deg,#8B5CF6,#3B82F6)' },
        { text: '"BI paneli bizga birinchi marta real vaqt rejimida biznesimizga ko\'rinish berdi. Ijroiya darajasida qaror qabul qilish uchun o\'yin o\'zgartiruvchi."', name: 'Roman Muxitdinov', role: 'CFO, PropVision Group', initials: 'RM', grad: 'linear-gradient(135deg,#059669,#3B82F6)' },
      ],
    },
    cta: {
      tag: "O'sishga tayyormisiz?",
      title: "Keling, biznesingizni",
      titleGrad: 'birga o\'stiramiz',
      sub: "Bepul 30 daqiqalik strategiya qo'ng'irog'ini band qiling.",
      btnPrimary: 'Loyiha boshlash',
      btnTelegram: "Telegram'da yozish",
    },
    contact: {
      tag: 'Aloqa',
      title: 'Loyihangiz haqida',
      titleGrad: 'aytib bering',
      sub: "Ish kunlarida 4 soat ichida javob beramiz.",
      labelName: 'Ismingiz',
      labelEmail: 'Email manzil',
      labelCompany: 'Kompaniya / Veb-sayt',
      labelDesc: 'Loyiha tavsifi',
      placeholderName: 'Abdulloh Karimov',
      placeholderEmail: 'abdulloh@company.com',
      placeholderCompany: 'company.com (ixtiyoriy)',
      placeholderDesc: "Loyihangiz, maqsadlaringiz va muddatingiz haqida aytib bering...",
      submit: 'Xabar yuborish',
      submitted: '✓ Xabar yuborildi!',
      telegramLabel: 'Telegram',
      telegramHandle: '@reworagencybot',
      emailLabel: 'Email',
      emailVal: 'hello@reworkagency.com',
      locationLabel: 'Manzil',
      locationVal: 'Toshkent, O\'zbekiston',
    },
    footer: {
      tagline: "Zamonaviy veb, avtomatlashtirish va marketing orqali biznes o'sishiga yordam beruvchi raqamli yechimlar.",
      services: 'Xizmatlar',
      company: 'Kompaniya',
      contact: 'Aloqa',
      copyright: "© 2025 Rework Agency. Barcha huquqlar himoyalangan.",
      links: {
        webDev: 'Veb-ishlab chiqish',
        uiux: 'UI/UX Dizayn',
        ads: 'Maqsadli reklama',
        smm: 'SMM',
        chatbot: 'Chatbot',
        bi: 'BI Tahlil',
        home: 'Bosh sahifa',
        cases: 'Loyihalar',
        about: 'Biz haqimizda',
        blog: 'Blog',
        contacts: 'Aloqa',
        telegram: 'Telegram Bot',
        instagram: 'Instagram',
        linkedin: 'LinkedIn',
      },
    },
    pages: {
      servicesTitle: 'Barcha xizmatlar',
      servicesSub: "Biznesingizni raqamli o'stirish uchun hamma narsa.",
      casesTitle: 'Loyihalar',
      casesSub: "O'lchanadigan natijali haqiqiy loyihalar.",
      aboutTitle: 'Rework Agency haqida',
      aboutSub: "Biz dizaynerlar, muhandislar va o'sish strateglari jamoasimiz.",
      aboutBody: "2025 yilda tashkil etilgan Rework Agency e-commerce, fintech, ko'chmas mulk va sog'liqni saqlash sohalaridagi 80+ kompaniyaga raqamli mavjudligini o'zgartirishga yordam berdi.",
      blogTitle: 'Blog va tushunchalar',
      blogSub: "Dizayn, o'sish va raqamli transformatsiya haqida fikrlar.",
      contactsTitle: 'Biz bilan bog\'laning',
      contactsSub: 'Loyihangizni muhokama qilaylik.',
    },
  },
}

const state = reactive({ lang: 'en' })

export function useLang() {
  const setLang = (lang) => {
    state.lang = lang
    currentLang.value = lang
    localStorage.setItem('rework-lang', lang)
  }

  const t = (key) => {
    const keys = key.split('.')
    let val = translations[state.lang]
    for (const k of keys) {
      val = val?.[k]
    }
    return val ?? key
  }

  const initLang = () => {
    const saved = localStorage.getItem('rework-lang')
    if (saved && translations[saved]) setLang(saved)
  }

  return { lang: state, setLang, t, initLang, currentLang: state }
}
